---
# (!) DO NOT CHANGE (!)
version: 2.1.0

settings:
  # Default sound to play for each announcement.
  # Use '' (empty string) to disable.
  # Use this for a list of available sounds: https://wiki.bedrock.dev/documentation/sound-definitions.html
  sound: 'random.levelup'

  # The prefix message
  # Use '&' for colors
  prefix: "&r&8[&aAA&8] "

  # enable/disable the use of prefixes.
  # true = on, false = off
  use-prefix: true

  # Interval between each message in seconds
  interval: 60

  # If the messages should be sent in order they're formatted in
  # or if they should send at random.
  random: true

# List of messages to be broadcasted
# Each message block supports:
#   - text: array of lines (use '&' for colors)
#   - sound: optional sound (overrides default); set '' to disable for this message
#   - temporary: if true, message will only cycle until removed or expired
#   - cycles: number of times to broadcast this message if temporary (ignored if temporary=false)
messages:
  - text:
      - "&r&aWelcome to the server!"
      - "&r&7Read /rules!"
    sound: 'random.toast'
    temporary: false
    cycles: 0

  - text:
      - "&r&7Enjoy your stay!"
    sound: ''
    temporary: false
    cycles: 0

  - text:
      - "&r&6Visit our website at example.com"
    sound: 'note.pling'
    temporary: true
    cycles: 5
